// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: MotorState.proto at 7:1
package com.johnanderson.pinewoodderbybleshared.models;

import android.os.Parcelable;
import com.squareup.wire.AndroidMessage;
import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class MotorState extends AndroidMessage<MotorState, MotorState.Builder> {
  public static final ProtoAdapter<MotorState> ADAPTER = new ProtoAdapter_MotorState();

  public static final Parcelable.Creator<MotorState> CREATOR = AndroidMessage.newCreator(ADAPTER);

  private static final long serialVersionUID = 0L;

  public static final Double DEFAULT_SPEED = 0.0d;

  public static final Boolean DEFAULT_TEST = false;

  /**
   * Speed of the motor (-100 to 100), negative will be reverse
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#DOUBLE",
      label = WireField.Label.REQUIRED
  )
  public final Double speed;

  /**
   * just a test boolean to play with
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL",
      label = WireField.Label.REQUIRED
  )
  public final Boolean test;

  public MotorState(Double speed, Boolean test) {
    this(speed, test, ByteString.EMPTY);
  }

  public MotorState(Double speed, Boolean test, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.speed = speed;
    this.test = test;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.speed = speed;
    builder.test = test;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof MotorState)) return false;
    MotorState o = (MotorState) other;
    return unknownFields().equals(o.unknownFields())
        && speed.equals(o.speed)
        && test.equals(o.test);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + speed.hashCode();
      result = result * 37 + test.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", speed=").append(speed);
    builder.append(", test=").append(test);
    return builder.replace(0, 2, "MotorState{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<MotorState, Builder> {
    public Double speed;

    public Boolean test;

    public Builder() {
    }

    /**
     * Speed of the motor (-100 to 100), negative will be reverse
     */
    public Builder speed(Double speed) {
      this.speed = speed;
      return this;
    }

    /**
     * just a test boolean to play with
     */
    public Builder test(Boolean test) {
      this.test = test;
      return this;
    }

    @Override
    public MotorState build() {
      if (speed == null
          || test == null) {
        throw Internal.missingRequiredFields(speed, "speed",
            test, "test");
      }
      return new MotorState(speed, test, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_MotorState extends ProtoAdapter<MotorState> {
    ProtoAdapter_MotorState() {
      super(FieldEncoding.LENGTH_DELIMITED, MotorState.class);
    }

    @Override
    public int encodedSize(MotorState value) {
      return ProtoAdapter.DOUBLE.encodedSizeWithTag(1, value.speed)
          + ProtoAdapter.BOOL.encodedSizeWithTag(3, value.test)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, MotorState value) throws IOException {
      ProtoAdapter.DOUBLE.encodeWithTag(writer, 1, value.speed);
      ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.test);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public MotorState decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.speed(ProtoAdapter.DOUBLE.decode(reader)); break;
          case 3: builder.test(ProtoAdapter.BOOL.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public MotorState redact(MotorState value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
